export const ADD_TODO = 'ADD_TODO'
export const TOGGLE_TODO = 'TOGGLE_TODO'
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE'

export const FETCH_EMPLOYEE_PENDING = 'FETCH_EMPLOYEE_PENDING';
export const FETCH_EMPLOYEE_SUCCESS = 'FETCH_EMPLOYEE_SUCCESS';
export const FETCH_EMPLOYEE_ERROR = 'FETCH_PRODUCTS_ERROR';
export const GET_ALL_EMPLOYEE = 'GET_ALL_EMPLOYEE';
export const FILTER_EMPLOYEE_BY = 'FILTER_EMPLOYEE_BY';



export const VisibilityFilters = {
  SHOW_ALL: 'SHOW_ALL',
  SHOW_COMPLETED: 'SHOW_COMPLETED',
  SHOW_ACTIVE: 'SHOW_ACTIVE'
}